export const allow_change = true;
export const btn_color = "#931F1D";
export const next_btn_color = "#eb2335";
export const btn_text = "One Click Offer ⇄";

export const bg_primary = "#020202";
export const bg_secondary = "#0D2818";
export const color_text_dark = "#0D1321";
export const color_text_light = "#FFEDDF";
export const DEBUG = false;

// Items which are priced with half-scrap precision on backpack.tf
export const itemsWithPriceHalfScrap = new Set([
    "Rocket Jumper",
    "Quick-Fix",
    "Sticky Jumper",
    "Air Strike",
    "Ali Baba's Wee Booties",
    "Ambassador",
    "Amputator",
    "Atomizer",
    "Axtinguisher",
    "B.A.S.E. Jumper",
    "Baby Face's Blaster",
    "Back Scatter",
    "Back Scratcher",
    "Backburner",
    "Battalion's Backup",
    "Bazaar Bargain",
    "Beggar's Bazooka",
    "Big Earner",
    "Black Box",
    "Blutsauger",
    "Bonk! Atomic Punch",
    "Bootlegger",
    "Boston Basher",
    "Brass Beast",
    "Buff Banner",
    "Buffalo Steak Sandvich",
    "Bushwacka",
    "Candy Cane",
    "Chargin' Targe",
    "Claidheamh Mòr",
    "Classic",
    "Cleaner's Carbine",
    "Cloak and Dagger",
    "Concheror",
    "Conniver's Kunai",
    "Cow Mangler 5000",
    "Cozy Camper",
    "Crit-a-Cola",
    "Crusader's Crossbow",
    "Dalokohs Bar",
    "Darwin's Danger Shield",
    "Dead Ringer",
    "Degreaser",
    "Detonator",
    "Diamondback",
    "Direct Hit",
    "Disciplinary Action",
    "Dragon's Fury",
    "Enforcer",
    "Equalizer",
    "Escape Plan",
    "Eureka Effect",
    "Eviction Notice",
    "Eyelander",
    "Family Business",
    "Fan O'War",
    "Fists of Steel",
    "Flare Gun",
    "Flying Guillotine",
    "Force-A-Nature",
    "Fortified Compound",
    "Frontier Justice",
    "Gas Passer",
    "Gloves of Running Urgently",
    "Gunboats",
    "Gunslinger",
    "Half-Zatoichi",
    "Hitman's Heatmaker",
    "Holiday Punch",
    "Holy Mackerel",
    "Homewrecker",
    "Hot Hand",
    "Huntsman",
    "Huo-Long Heater",
    "Iron Bomber",
    "Jag",
    "Jarate",
    "Killing Gloves of Boxing",
    "Kritzkrieg",
    "L'Etranger",
    "Liberty Launcher",
    "Loch-n-Load",
    "Lollichop",
    "Loose Cannon",
    "Machina",
    "Mad Milk",
    "Manmelter",
    "Mantreads",
    "Market Gardener",
    "Natascha",
    "Neon Annihilator",
    "Nessie's Nine Iron",
    "Original",
    "Overdose",
    "Pain Train",
    "Panic Attack",
    "Persian Persuader",
    "Phlogistinator",
    "Pomson 6000",
    "Postal Pummeler",
    "Powerjack",
    "Pretty Boy's Pocket Pistol",
    "Quickiebomb Launcher",
    "Rainblower",
    "Razorback",
    "Red-Tape Recorder",
    "Rescue Ranger",
    "Reserve Shooter",
    "Righteous Bison",
    "Sandman",
    "Sandvich",
    "Scorch Shot",
    "Scotsman's Skullcutter",
    "Scottish Handshake",
    "Scottish Resistance",
    "Second Banana",
    "Shahanshah",
    "Sharpened Volcano Fragment",
    "Short Circuit",
    "Shortstop",
    "Soda Popper",
    "Solemn Vow",
    "Southern Hospitality",
    "Splendid Screen",
    "Spy-cicle",
    "Sun-on-a-Stick",
    "Sydney Sleeper",
    "Thermal Thruster",
    "Third Degree",
    "Tide Turner",
    "Tomislav",
    "Tribalman's Shiv",
    "Ubersaw",
    "Ullapool Caber",
    "Vita-Saw",
    "Warrior's Spirit",
    "Widowmaker",
    "Winger",
    "Wrangler",
    "Wrap Assassin",
    "Your Eternal Reward"
]);
