export const allow_change = true;
export const btn_color = "#931F1D";
export const next_btn_color = "#eb2335";
export const btn_text = "One Click Offer ⇄";

export const bg_primary = "#020202";
export const bg_secondary = "#0D2818";
export const color_text_dark = "#0D1321";
export const color_text_light = "#FFEDDF";
export const DEBUG = false;

// Items which are priced with half-scrap precision on backpack.tf
export const itemsWithPriceHalfScrap = new Set([
    "The Rocket Jumper",
    "The Quick-Fix",
    "The Sticky Jumper",
    "The Air Strike",
    "Ali Baba's Wee Booties",
    "The Ambassador",
    "The Amputator",
    "The Atomizer",
    "The Axtinguisher",
    "The B.A.S.E. Jumper",
    "Baby Face's Blaster",
    "The Back Scatter",
    "The Back Scratcher",
    "The Backburner",
    "The Battalion's Backup",
    "The Bazaar Bargain",
    "The Beggar's Bazooka",
    "The Big Earner",
    "The Black Box",
    "The Blutsauger",
    "Bonk! Atomic Punch",
    "The Bootlegger",
    "The Boston Basher",
    "The Brass Beast",
    "The Buff Banner",
    "The Buffalo Steak Sandvich",
    "The Bushwacka",
    "The Candy Cane",
    "The Chargin' Targe",
    "The Claidheamh Mòr",
    "The Classic",
    "The Cleaner's Carbine",
    "The Cloak and Dagger",
    "The Concheror",
    "Conniver's Kunai",
    "The Cow Mangler 5000",
    "The Cozy Camper",
    "Crit-a-Cola",
    "Crusader's Crossbow",
    "The Dalokohs Bar",
    "Darwin's Danger Shield",
    "The Dead Ringer",
    "The Degreaser",
    "Detonator",
    "The Diamondback",
    "The Direct Hit",
    "The Disciplinary Action",
    "The Dragon's Fury",
    "The Enforcer",
    "The Equalizer",
    "The Escape Plan",
    "The Eureka Effect",
    "The Eviction Notice",
    "The Eyelander",
    "The Family Business",
    "The Fan O'War",
    "The Fists of Steel",
    "The Flare Gun",
    "The Flying Guillotine",
    "The Force-A-Nature",
    "The Fortified Compound",
    "Frontier Justice",
    "The Gas Passer",
    "Gloves of Running Urgently",
    "The Gunboats",
    "The Gunslinger",
    "The Half-Zatoichi",
    "The Hitman's Heatmaker",
    "The Holiday Punch",
    "The Holy Mackerel",
    "The Homewrecker",
    "The Hot Hand",
    "The Huntsman",
    "The Huo-Long Heater",
    "The Iron Bomber",
    "The Jag",
    "Jarate",
    "The Killing Gloves of Boxing",
    "The Kritzkrieg",
    "L'Etranger",
    "The Liberty Launcher",
    "The Loch-n-Load",
    "The Lollichop",
    "The Loose Cannon",
    "The Machina",
    "Mad Milk",
    "The Manmelter",
    "The Mantreads",
    "The Market Gardener",
    "Natascha",
    "The Neon Annihilator",
    "Nessie's Nine Iron",
    "The Original",
    "The Overdose",
    "The Pain Train",
    "The Panic Attack",
    "The Persian Persuader",
    "The Phlogistinator",
    "The Pomson 6000",
    "The Postal Pummeler",
    "The Powerjack",
    "Pretty Boy's Pocket Pistol",
    "The Quickiebomb Launcher",
    "The Rainblower",
    "The Razorback",
    "The Red-Tape Recorder",
    "The Rescue Ranger",
    "The Reserve Shooter",
    "The Righteous Bison",
    "The Sandman",
    "The Sandvich",
    "The Scorch Shot",
    "The Scotsman's Skullcutter",
    "The Scottish Handshake",
    "The Scottish Resistance",
    "The Second Banana",
    "The Shahanshah",
    "Sharpened Volcano Fragment",
    "The Short Circuit",
    "The Shortstop",
    "The Soda Popper",
    "The Solemn Vow",
    "The Southern Hospitality",
    "The Splendid Screen",
    "The Spy-cicle",
    "The Sun-on-a-Stick",
    "The Sydney Sleeper",
    "The Thermal Thruster",
    "The Third Degree",
    "The Tide Turner",
    "Tomislav",
    "The Tribalman's Shiv",
    "The Ubersaw",
    "The Ullapool Caber",
    "The Vita-Saw",
    "The Warrior's Spirit",
    "The Widowmaker",
    "The Winger",
    "The Wrangler",
    "The Wrap Assassin",
    "Your Eternal Reward"
]);
